version: "3.7"

services:
  lfs:
    image: ghcr.io/samarsha/giftless-extras
    restart: always
    environment:
      - GIFTLESS_CONFIG_FILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports: [127.0.0.1:5000:5000]
    volumes:
      - /opt/git/giftless.yaml:/app/config.yaml
      - /opt/git/jwt-rs256.key.pub:/app/jwt-rs256.key.pub
